// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACs22brGSzrNrIdi2Frqy5BeuN-FTTS9E',
    appId: '1:236169692445:web:538ac2d198bc3e33484df4',
    messagingSenderId: '236169692445',
    projectId: 'flutter-student-app-6bb9e',
    authDomain: 'flutter-student-app-6bb9e.firebaseapp.com',
    storageBucket: 'flutter-student-app-6bb9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7c_m2yfuv6pLPvULytW2P_Y_fH-YQPXI',
    appId: '1:236169692445:android:44f43c47e5156b8f484df4',
    messagingSenderId: '236169692445',
    projectId: 'flutter-student-app-6bb9e',
    storageBucket: 'flutter-student-app-6bb9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7dXv0ZpkShnMVNjHQ46Ge2JHHx-W1jM',
    appId: '1:236169692445:ios:2a46b687ff766e21484df4',
    messagingSenderId: '236169692445',
    projectId: 'flutter-student-app-6bb9e',
    storageBucket: 'flutter-student-app-6bb9e.appspot.com',
    androidClientId: '236169692445-lnk2cogtqedn95ssuk4hkcjkl9984dju.apps.googleusercontent.com',
    iosClientId: '236169692445-q1bgsvq4g6t7t9hos124q18aots33n6q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogrenciApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7dXv0ZpkShnMVNjHQ46Ge2JHHx-W1jM',
    appId: '1:236169692445:ios:e2f28b1a1f16057f484df4',
    messagingSenderId: '236169692445',
    projectId: 'flutter-student-app-6bb9e',
    storageBucket: 'flutter-student-app-6bb9e.appspot.com',
    androidClientId: '236169692445-lnk2cogtqedn95ssuk4hkcjkl9984dju.apps.googleusercontent.com',
    iosClientId: '236169692445-mfrd7a62s4riejq76pm8113ne8552qtm.apps.googleusercontent.com',
    iosBundleId: 'com.example.ogrenciApp.RunnerTests',
  );
}
